# Generated by Django 3.0.7 on 2021-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposditivo_medico',
            name='Fecha_de_Adquisición',
            field=models.DateTimeField(verbose_name='date adquisision'),
        ),
        migrations.AlterField(
            model_name='disposditivo_medico',
            name='Fecha_de_Instalación',
            field=models.DateTimeField(verbose_name='date instalation'),
        ),
    ]
