# Generated by Django 3.0.7 on 2021-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='meduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='meduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MedUser',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
